# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b73df30f58061ebe174fedc9ffa3a2e37365018384078adb7e197d662b79130b5a21f8b6104010934c3ccd44121584e4ee7cd7a89da88e52746d52048aede7d

test:
  secret_key_base: 072c9fa263823d41167524bf1fdca887e427038e816e7035af5a54b3907104fe72240ce485f511db996271ee269b87f6790e6034aafa1142004e759ea2641588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
